=== rdorden/MAGIC-GAME/DTD2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT juego (lista_cartas+)>
<!ATTLIST juego
titulo CDATA #REQUIRED
autor CDATA #REQUIRED
version CDATA #REQUIRED >
<!ELEMENT lista_cartas (carta_entorno*, carta_ser*,carta_intervecion*)>
<!ELEMENT carta_entorno (coste,comportamiento)>
<!ATTLIST carta_entorno
	codigo CDATA #REQUIRED
	nombre CDATA #REQUIRED
	max CDATA #REQUIRED
	clase (mar|aire|tierra|espiritu|mar) #REQUIRED
	tipo CDATA #REQUIRED
	imagen CDATA #REQUIRED>

<!ELEMENT carta_ser (coste,comportamiento)>
<!ATTLIST carta_ser
	codigo CDATA #REQUIRED
	nombre CDATA #REQUIRED
	max CDATA #REQUIRED
	clase (mar|aire|tierra|espiritu|mar) #REQUIRED
	tipo CDATA #REQUIRED
	imagen CDATA #REQUIRED
	ataque CDATA #REQUIRED
	defensa CDATA #REQUIRED>

<!ELEMENT carta_intervencion (coste,comportamiento)>
<!ATTLIST carta_intervencion
	codigo CDATA #REQUIRED
	nombre CDATA #REQUIRED
	max CDATA #REQUIRED
	clase (mar|aire|tierra|espiritu|mar) #REQUIRED
	tipo CDATA #REQUIRED
	imagen CDATA #REQUIRED>

<!ELEMENT comportamiento EMPTY>
<!ATTLIST comportamiento
	descripcion CDATA #REQUIRED
	codigo CDATA #IMPLIED
	variable1 CDATA #IMPLIED
	variable2 CDATA #IMPLIED
	variable3 (mar|aire|tierra|espiritu|mar) #IMPLIED>

<!ELEMENT coste EMPTY>
<!ATTLIST coste
	aire CDATA #IMPLIED
	mar CDATA #IMPLIED
	tierra CDATA #IMPLIED
	espiritu CDATA #IMPLIED
	generico CDATA #IMPLIED>

=== rdorden/MAGIC-GAME/XMLPRUEBAS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juego SYSTEM "DTD2.dtd">
<juego titulo="Brujos y Trifulcas" autor="David Ateza Rubio, Jose Agustin Diaz Del Aguila Boquete, Rodrigo De La Orden" version="5.0">
<lista_cartas>
	<carta_entorno codigo="corriente" nombre="Corriente de Tempano" ejemplares="3" clase="mar" tipo="entorno" imagen="res\\imagenes\\corriente.jpg">
		<coste aire="1" generico="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1A + 1 generico al banco de cloro del brujo que lo controla" codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="desierto" nombre="Desierto Austral" ejemplares="-1" clase="tierra" tipo="entorno" imagen="res\\imagenes\\desierto.jpg">
		<coste tierra="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1T al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="fosa" nombre="Fosa Septica" ejemplares="-1" clase="mar" tipo="entorno" imagen="res\\imagenes\\fosa.jpg">
		<coste mar="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1M al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>
	<carta_entorno codigo="nave" nombre="Nave del Misterio" ejemplares="-1" clase="espiritu" tipo="entorno" imagen="res\\imagenes\\nave.jpg">
		<coste espiritu="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1E al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="nube" nombre="Nube Borascosa" ejemplares="-1" clase="aire" tipo="entorno" imagen="res\\imagenes\\nube.jpg">
		<coste aire="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1A al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="peninsula" nombre="Peninsula Emerita" ejemplares="3" clase="mar" tipo="entorno" imagen="res\\imagenes\\peninsula.jpg">
		<coste mar="1" generico="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1M + 1 generico al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="portal" nombre="Portal Intra-Mundos" ejemplares="3" clase="espiritu" tipo="entorno" imagen="res\\imagenes\\portal.jpg">
		<coste espiritu="3"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 3E al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="prado" nombre="Prado Infantil" ejemplares="3" clase="tierra" tipo="entorno" imagen="res\\imagenes\\prado.jpg">
		<coste tierra="1" generico="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1T + 1 generico al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="erial" nombre="Erial Glamuroso" ejemplares="-1" clase="tierra" tipo="entorno" imagen="res\\imagenes\\erial.jpg">
		<coste tierra="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1T al banco de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_entorno codigo="isla" nombre="Isla de Lesbos" ejemplares="1" clase="mar" tipo="entorno" imagen="res\\imagenes\\isla.jpg">
		<coste mar="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1M al banco de cloro del brujo que lo controla. Ademas, si el brujo que controla la Isla de Lesbos solo controla entornos de clase Mar, se aniaden NM adicionales a su banco de cloro, siendo N el numero de entornos de clase Mar que controla el brujo." codigo="SumaCloroAdicional" variable3="mar"/>
	</carta_entorno>

	<carta_entorno codigo="nodo" nombre="Nodo Necromental" ejemplares="3" clase="espiritu" tipo="entorno" imagen="res\\imagenes\\nodo.jpg">
		<coste espiritu="1"/>
		<comportamiento descripcion="Al descargar este entorno, se aniade 1E al banco de cloro del brujo que lo controla. Ademas, todos los cloros que haya en ese momento en el banco de cloro del brujo que lo controla se convierten en cloros de clase Espiritu, sean genericos o de cualquier otra clase." codigo="TransformacionCloros" variable3="espiritu"/>
	</carta_entorno>
	
	<carta_entorno codigo="caos" nombre="Caos del Mundo" ejemplares="2" clase="Espiritu" tipo="entorno" imagen="res\\imagenes\\caos.jpg">
		<coste tierra="3"/>
		<comportamiento descripcion="Al descargar el Caos del Mundo, aÃ±ande 1E, 1T, 1A, 1M y 1G a la reserva de cloro del brujo que lo controla." codigo="ComportamientoEntorno"/>
	</carta_entorno>

	<carta_ser codigo="aberracion" nombre="Aberracion Poltergeist" ejemplares="3" clase="espitiru" tipo="ser" imagen="res\\imagenes\\aberracion.jpg" ataque="2" defensa="2">
		<coste espiritu="1" generico="2"/>
		<comportamiento descripcion="El comportamiento especial de la Aberracion Poltergeist solo se activa en la fase de trifulca, siempre y cuando este ser este asignado como defensor de algun otro ser atacante. Ademas, la activacion de este comportamiento especial es optativa, el brujo que controla a este ser puede decidir, en el momento oportuno, si quiere o no quiere activarlo. Cuando se activa este comportamiento especial, todos los atributos de la Aberracion Poltergeist (nombre, codigo, tipo, clase, ataque, defensa, coste, ejemplares, comportamientos especiales, etc.) cambian para pasar a ser iguales a los del ser atacante. A partir de entonces, a todos los efectos es como si la Aberracion Poltergeist hubiese dejado de existir." codigo="Copiar"/>
	</carta_ser>

	<carta_ser codigo="albatros" nombre="Albatros Legendario" ejemplares="1" clase="aire" tipo="ser" imagen="res\\imagenes\\albatros.jpg" ataque="2" defensa="3">
		<coste aire="1" generico="2"/>
		<comportamiento descripcion="El comportamiento especial del Albatros Legendario solo se activa en la fase de trifulca, siempre y cuando este ser haya sido elegido como atacante. Cuando se activa este comportamiento especial, ningun ser de clase Aire puede ser asignado como defensor del Albatros Legendario." codigo="NoDefensores" variable3="aire"/>
	</carta_ser>

	<carta_ser codigo="angel" nombre="Angel de la Debacle" ejemplares="2" clase="espiritu" tipo="ser" imagen="res\\imagenes\\angel.jpg" ataque="6" defensa="2">
		<coste espiritu="3" generico="2"/>
		<comportamiento descripcion="El comportamiento especial del Angel de la Debacle solo se activa en la fase de trifulca, siempre y cuando este ser haya sido elegido como atacante. Cuando se activa este comportamiento especial, el Angel de la Debacle suma N-1 puntos a su atributo de defensa siendo N el numero de defensores que tenga asignados." codigo="SumaEnAtaque2" variable1="1" variable2="1" variable3="null"/>
	</carta_ser>

	<carta_ser codigo="ballena" nombre="Ballena Monje" ejemplares="3" clase="mar" tipo="ser" imagen="res\\imagenes\\ballena.jpg" ataque="1" defensa="5">
		<coste mar="2" generico="2"/>
		<comportamiento descripcion="El comportamiento especial de la Ballena Monje solo se activa en la fase de trifulca, siempre y cuando este ser este asignado como defensor de algun otro ser atacante. Cuando se activa este comportamiento especial, la Ballena Monje resta 2 puntos a su atributo de defensa si esta asignada como defensora de un ser atacante de clase Aire." codigo="SumaEnDefensa" variable1="0" variable2="-2" variable3="aire"/>
	</carta_ser>

	<carta_ser codigo="caballero" nombre="Caballero Tremebundo" ejemplares="1" clase="tierra" tipo="ser" imagen="res\\imagenes\\caballero.jpg" ataque="3" defensa="2">
		<coste tierra="2" generico="1"/>
		<comportamiento descripcion="El comportamiento especial del Caballero Tremebundo solo se activa en la fase de trifulca, siempre y cuando este ser haya sido elegido como atacante. Cuando se activa este comportamiento especial, el Caballero Tremebundo suma N puntos a su atributo de ataque y N puntos a su atributo de defensa siendo N el numero de defensores de clase Espiritu que tenga asignados." codigo="SumaEnAtaque" variable1="1" variable2="1" variable3="espiritu"/>
	</carta_ser>

	<carta_ser codigo="cucaracha" nombre="Cucaracha Indomita" ejemplares="-1" clase="tierra" tipo="ser" imagen="res\\imagenes\\cucaracha.jpg" ataque="1" defensa="2">
		<coste generico="2"/>
		<comportamiento descripcion="El comportamiento especial de este ser se activa en cuanto se juega cualquier intervencion, impidiendo que se pueda escoger como objeto de dicha intervencion a la Cucaracha Indomita." codigo="NoIntervenciones"/>
	</carta_ser>

	<carta_ser codigo="elemental" nombre="Elemental de Lluvia" ejemplares="2" clase="mar" tipo="ser" imagen="res\\imagenes\\elemental.jpg" ataque="3" defensa="3">
		<coste mar="3" generico="1"/>
		<comportamiento descripcion="El comportamiento especial del Elemental de Lluvia se activa al terminar la fase de trifulca (es decir, habiendo ya resuelto la trifulca y la muerte de seres), siempre y cuando este ser haya actuado durante dicha trifulca como defensor de algun otro ser atacante. Cuando se activa este comportamiento especial, si dicho ser atacante sigue en la zona de juego, regresa a la mano del brujo que lo controla" codigo="DevolverMano"/>
	</carta_ser>

	<carta_ser codigo="espectro" nombre="Espectro Vampirico" ejemplares="3" clase="espiritu" tipo="ser" imagen="res\\imagenes\\espectro.jpg" ataque="1" defensa="1">
		<coste espiritu="1"/>
